user:
  max_name: 50
  min_name: 3
  max_password: 250
  min_password: 6
images:
  accepted_files: "image/jpeg, image/gif, image/png"
post:
  max_title: 250
  min_title: 6
  min_content: 6
  types:
    question: "question"
    article: "article"
series:
  max_title: 250
  min_title: 6
tag:
  limit_for_search: 5
  max_name: 50
  min_name: 3
reply:
  limit_for_children_replies: 3
zero: 0
one: 1
paginate_default: 10
paginate_tags: 9
paginate_little: 5
paginate_index: 3
paginate_user: 8
paginate_series: 5
paginate_post: 6
reaction:
  like: "like"
  spam: "spam"
  upvote: "upvote"
  downvote: "downvote"
view_timeout: 15
point:
  ten: 10
  twenty: 20
series:
  max_title: 60
